//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bodegaAPP.ProductosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/productosbodegaWSSOAP.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idbodegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idcategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idproductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idbodega {
            get {
                return this.idbodegaField;
            }
            set {
                if ((object.ReferenceEquals(this.idbodegaField, value) != true)) {
                    this.idbodegaField = value;
                    this.RaisePropertyChanged("idbodega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcategoria {
            get {
                return this.idcategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.idcategoriaField, value) != true)) {
                    this.idcategoriaField = value;
                    this.RaisePropertyChanged("idcategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idproducto {
            get {
                return this.idproductoField;
            }
            set {
                if ((object.ReferenceEquals(this.idproductoField, value) != true)) {
                    this.idproductoField = value;
                    this.RaisePropertyChanged("idproducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/productosbodegaWSSOAP.Errores")]
    [System.SerializableAttribute()]
    public partial class ErroresException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductosService.IProductoService")]
    public interface IProductoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/CrearProducto", ReplyAction="http://tempuri.org/IProductoService/CrearProductoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(bodegaAPP.ProductosService.ErroresException), Action="http://tempuri.org/IProductoService/CrearProductoErroresExceptionFault", Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/productosbodegaWSSOAP.Errores")]
        bodegaAPP.ProductosService.Producto CrearProducto(bodegaAPP.ProductosService.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/CrearProducto", ReplyAction="http://tempuri.org/IProductoService/CrearProductoResponse")]
        System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto> CrearProductoAsync(bodegaAPP.ProductosService.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ObtenerProducto", ReplyAction="http://tempuri.org/IProductoService/ObtenerProductoResponse")]
        bodegaAPP.ProductosService.Producto ObtenerProducto(string idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ObtenerProducto", ReplyAction="http://tempuri.org/IProductoService/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto> ObtenerProductoAsync(string idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ModificarProducto", ReplyAction="http://tempuri.org/IProductoService/ModificarProductoResponse")]
        bodegaAPP.ProductosService.Producto ModificarProducto(bodegaAPP.ProductosService.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ModificarProducto", ReplyAction="http://tempuri.org/IProductoService/ModificarProductoResponse")]
        System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto> ModificarProductoAsync(bodegaAPP.ProductosService.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/EliminarProducto", ReplyAction="http://tempuri.org/IProductoService/EliminarProductoResponse")]
        void EliminarProducto(string idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/EliminarProducto", ReplyAction="http://tempuri.org/IProductoService/EliminarProductoResponse")]
        System.Threading.Tasks.Task EliminarProductoAsync(string idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarProductos", ReplyAction="http://tempuri.org/IProductoService/ListarProductosResponse")]
        bodegaAPP.ProductosService.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarProductos", ReplyAction="http://tempuri.org/IProductoService/ListarProductosResponse")]
        System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto[]> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarPorBodega", ReplyAction="http://tempuri.org/IProductoService/ListarPorBodegaResponse")]
        bodegaAPP.ProductosService.Producto[] ListarPorBodega(string idbodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarPorBodega", ReplyAction="http://tempuri.org/IProductoService/ListarPorBodegaResponse")]
        System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto[]> ListarPorBodegaAsync(string idbodega);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoServiceChannel : bodegaAPP.ProductosService.IProductoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoServiceClient : System.ServiceModel.ClientBase<bodegaAPP.ProductosService.IProductoService>, bodegaAPP.ProductosService.IProductoService {
        
        public ProductoServiceClient() {
        }
        
        public ProductoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bodegaAPP.ProductosService.Producto CrearProducto(bodegaAPP.ProductosService.Producto productoACrear) {
            return base.Channel.CrearProducto(productoACrear);
        }
        
        public System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto> CrearProductoAsync(bodegaAPP.ProductosService.Producto productoACrear) {
            return base.Channel.CrearProductoAsync(productoACrear);
        }
        
        public bodegaAPP.ProductosService.Producto ObtenerProducto(string idproducto) {
            return base.Channel.ObtenerProducto(idproducto);
        }
        
        public System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto> ObtenerProductoAsync(string idproducto) {
            return base.Channel.ObtenerProductoAsync(idproducto);
        }
        
        public bodegaAPP.ProductosService.Producto ModificarProducto(bodegaAPP.ProductosService.Producto productoAModificar) {
            return base.Channel.ModificarProducto(productoAModificar);
        }
        
        public System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto> ModificarProductoAsync(bodegaAPP.ProductosService.Producto productoAModificar) {
            return base.Channel.ModificarProductoAsync(productoAModificar);
        }
        
        public void EliminarProducto(string idproducto) {
            base.Channel.EliminarProducto(idproducto);
        }
        
        public System.Threading.Tasks.Task EliminarProductoAsync(string idproducto) {
            return base.Channel.EliminarProductoAsync(idproducto);
        }
        
        public bodegaAPP.ProductosService.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
        
        public bodegaAPP.ProductosService.Producto[] ListarPorBodega(string idbodega) {
            return base.Channel.ListarPorBodega(idbodega);
        }
        
        public System.Threading.Tasks.Task<bodegaAPP.ProductosService.Producto[]> ListarPorBodegaAsync(string idbodega) {
            return base.Channel.ListarPorBodegaAsync(idbodega);
        }
    }
}
